# Generated by Django 4.2.4 on 2023-09-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
