# Generated by Django 4.2.4 on 2023-08-28 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotografia',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
